server: 
  port: 5000
  servlet:
    context-path: /admin
spring:
  application:
    name: admin
  profiles:
    active:
      - dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
    sentinel:
      transport:
        dashboard: 127.0.0.1:5005
      eager: true



