server: 
  port: 5000
  servlet:
    context-path: /admin
spring:
  application:
    name: admin
  profiles:
    active:
      - dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
    sentinel:
      transport:
        dashboard: 127.0.0.1:5005
      eager: true
    rabbitmq:
      host: 127.0.0.1
      port: 5672
#      username: root
#      password: root
      #虚拟host 可以不设置,使用server默认host
      virtual-host: JCcccHost
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: own@three*123
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      timeout: 5000ms
      expireTime: 180


