server: 
  port: 5004
spring:
  application:
    name: gate
  profiles:
    active:
      - dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        enabled: true
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/yshop2?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml
    enabled: true
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


