spring:
  cloud:
    gateway:
      routes:
        - id: admin
          uri: lb://admin
#          uri: localhost:5000/admin/**
          predicates:
            - Path=/admin/**
#        - id: after_route
#            uri: https://example.org
#            predicates:
#              - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#        - id: before_route
#            uri: https://example.org
#            predicates:
#              - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
#        - id: between_route
#            uri: https://example.org
#            predicates:
#              - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
#        - id: cookie_route
#            uri: https://example.org
#            predicates:
#              - Cookie=chocolate, ch.p
#        - id: header_route
#            uri: https://example.org
#            predicates:
#              - Header=X-Request-Id, \d+
#        - id: host_route
#            uri: https://example.org
#            predicates:
#              - Host=**.somehost.org,**.anotherhost.org
#        - id: method_route
#            uri: https://example.org
#            predicates:
#              - Method=GET,POST
#        - id: path_route
#            uri: https://example.org
#            predicates:
#              - Path=/red/{segment},/blue/{segment}
#        - id: query_route
#            uri: https://example.org
#            predicates:
#              - Query=green
#        - id: remoteaddr_route
#            uri: https://example.org
#            predicates:
#              - RemoteAddr=192.168.1.1/24
##        权重路由
#        - id: weight_high
#            uri: https://weighthigh.org
#            predicates:
#              - Weight=group1, 8
#        - id: weight_low
#            uri: https://weightlow.org
#            predicates:
#              - Weight=group1, 2